### ISSUE TITLE
Missing Tissuumaps project file

### ISSUE THREAD

**Issue by arundasan91** [TissUUmaps/napari-tissuumaps#4]
Hello, 

Saving all layers with a `.tmap` extension saves all the point layers and images to a folder. However, it doesn't save a `.tmap` project file which I can open in Tissuumaps.

<img width="240" alt="image" src="https://user-images.githubusercontent.com/14352842/178516953-29130e83-7615-4f3d-ae27-55121b8c3454.png">

Could you please help?

Thanks,
Arun

**Comment by npielawski** [comment]
Hello Arun,

thanks for using this plugin!

When you export a project using this plugin it creates both a tmap file and a folder of the same name containing all the resources. There should then also be a file called “1_2c.tmap” in the upper folder.

Let me know if that works.

**Comment by arundasan91** [comment]
Hi Nicolas,

Thanks for the quick reply! I was expecting a `1_2c.tmap` file as well in the upper folder. However, there is none.
![image](https://user-images.githubusercontent.com/14352842/178561232-de33f11e-a5f7-4eec-b7af-65b483e450a7.png)


For a bit more context, here are the details of my system:

```
napari: 0.4.16rc2.dev126+g9beb1a0b
Platform: macOS-12.4-arm64-i386-64bit
System: MacOS 12.4
Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:33) [Clang 13.0.1 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.22.4
SciPy: 1.8.1
Dask: 2022.6.0
VisPy: 0.10.0

OpenGL:
- GL version: 2.1 Metal - 76.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1512x982, scale 2.0
- screen 2: resolution 2560x1440, scale 1.0

Plugins:
- console: 0.0.4
- napari-spatial-omics: 0.0.8
- napari-svg: 0.1.6
- napari-tissuumaps: 0.2.0
```

Thanks,
Arun

**Comment by npielawski** [comment]
Alright, I looked into it. The format is actually like this (I misremembered in my previous answer):
```
┌ file.tmap (the main folder)
├╴ main.tmap (the file to open in TissUUmaps)
├╴ images
└╴ points
```

I think the issue comes from Napari not using the napari-tissuumaps plugin at all since your folder structure and filenames are different. Can you describe the actions you performed in order to save the project?

**Comment by arundasan91** [comment]
Sure, these are the steps:

1. Open Napari (I installed the MacOS version).
2. Add an H&E image and a csv file with annotated points.
3. Hit `File -> Save All Layers`
4. Save to `1-2c_tissuumaps` folder with a filename of `1_2c.tmap`.

**Comment by npielawski** [comment]
Hello Arun, I double checked and it works on MacOS with the same plugin version that you have. Would you mind sharing your files with me or is the content sensitive? Otherwise, could you make a working example with a fake tif and csv?

Best,
Nicolas

**Comment by arundasan91** [comment]
Hi Nicolas,

This link should work for your email shown in your github profile: [Example Napari Images](https://pitt-my.sharepoint.com/:f:/g/personal/ard212_pitt_edu/EgEwUaZQ3uVOkd7IEnwpYGYB5l-uZnez0jDfbmEF2rVXmw?email=nicolas%40pielawski.fr&e=S1Cbn0)

Thanks,
Arun

**Comment by npielawski** [comment]
Great thanks!

So, `tissuumaps` as a dependency is not needed. I tried the example napari images and it worked here. I could load the file in TissUUmaps too.

Could you check in Napari: Plugins > Plugin Errors > select plugin to check if there is a problem with our plugin on the newer version of Napari? Also I have napari version 0.4.11 and it worked so maybe it's a version issue?

**Comment by arundasan91** [comment]
Hi @npielawski , the plugin is not working on my M1 Mac based on the versions I shared earlier. However, it worked on my Windows desktop. I believe M1 Mac is still not supported fully by Conda and QT. So I will close this ticket and use Windows for now.

**Comment by npielawski** [comment]
Hello @arundasan91, I looked more into the issue and Napari has completely changed their plugin system. They have a new plugin engine called npe2. I updated napari-tissuumaps to work with npe2 from now on, so feel free to try again.

Note that it won't work anymore if you just save the file as something.tmap, you need to choose the tmap extension in the drop down below when saving.
